Sprint 1
koracell/middle.messenger.praktikum.yandex pull request #1
Opened 2022-04-19 11:49 UTC by snblack

2022-04-24 13:39 UTC, Rodion-progs approved these changes
Все хорошо в основном. Отписал только по кодстайлу немного. Так же не заметил в проекте стилей дл hover и focus у кнопок и инпутов- но и дефолтные настройки не сброшены, поэтому можно и так. Но часто пишут свои стили для таких случаев. Стоит обратить внимание на БЭМ, почему- то не везде есть у элемента его блок в верстке. Понравилось что у картинок есть размеры в верстке, шаг к оптимизации отображения страницы.

2022-04-24 13:39 UTC, Rodion-progs commented on .gitignore
> +.parcel-cache/
Нужно исправить. Папку dist тоже стоит сюда добавить. Не нужно хранить собранные проект в гите, исходников достаточно

2022-04-24 13:39 UTC, Rodion-progs commented on dist/_redirects
> +/* /index.html 200
Можно лучше. Стоит добавлять пустую строку в конец файла, обычно под это настраивают линтер. Зачем это делать можно почитать тут https://semakin.dev/2020/05/no_newline_at_end_of_file/ про правило тут https://eslint.org/docs/rules/eol-last

2022-04-24 13:39 UTC, Rodion-progs commented on dist/_redirects
> +/* /index.html 200
А это dist файл, тогда неважно. Его вообще не должно быть тут. Писал об этом выше

2022-04-24 13:39 UTC, Rodion-progs commented on index.html
> +        <link rel="stylesheet" href="index.scss" />
Вообще подключают css, а не scss. css файл, который будет бандлом от сборки scss

2022-04-24 13:39 UTC, Rodion-progs commented on index.scss
> +    margin: 0px;
Можно лучше. px для 0 можно не указывать.

2022-04-24 13:39 UTC, Rodion-progs commented on server.js
> +const PORT = 3000;
Можно лучше. Порт лучше вынести в .env файл и брать из окружения этот порт. Пример можно глянуть тут https://habr.com/ru/company/ruvds/blog/351254/

2022-04-24 13:39 UTC, Rodion-progs commented on src/components/button/button.hbs
> +<button class="button {{klass}}">{{name}}</button>
Нужно исправить klass->class или className, потом можно самому запутаться, а как правильно писать. И лучше указывать атрибут  type для button, разные браузеры могут по дефолту разные type поставить

2022-04-24 13:39 UTC, Rodion-progs commented on src/components/chat_item/chat_item.hbs
> +        <div class='chat-item__last-meesage'>{{last_message}}</div>
Можно лучше. Лучше привыкать сразу писать правильно message. Немного развивает английский и читать приятнее

2022-04-24 13:39 UTC, Rodion-progs commented on src/components/chat_item/chat_item.hbs
> +<div class="chat-list__item">
Можно лучше. Если идти по БЭМ, то у блока должен быть ещё класс chat-item, а потом уже у блока могут быть элементы chat-item__content chat-item__name и так далее

2022-04-24 13:39 UTC, Rodion-progs commented on src/components/chat_item/chat_item.hbs
> +    <div class='avatar-small'><img src="{{image_link}}" alt="avatar" width="47" height="47"></div>
Тут хорошо, размеры для картинки чуть помогут браузеру при загрузки страницы. Alt думаю норм, если сайт на английском, что указано в index.html, иначе alt стоит писать на том языке на каком сам сайт будет

2022-04-24 13:39 UTC, Rodion-progs commented on src/components/chat_item/chat_item.tmpl.js
> +export const chat_item = ({name, last_message, date_last_message, image_link}) => chatTmpl({
Можно лучше. На фронте так исторически сложилось что все проекты пишутся lowerCamelCase. image_link -> imageLink

2022-04-24 13:39 UTC, Rodion-progs commented on src/components/field/field.hbs
> +<input type="text" class="input {{klass}}" name="{{name}}" placeholder="{{placeholder}}">
Про klass писал выше

2022-04-24 13:39 UTC, Rodion-progs commented on src/index.js
> +if(current_path == '/registration') {
1) можно лучше. Читабельне будет если заменить if на switch https://learn.javascript.ru/switch . 2) Надо исправить: избегать "==" и использовать "===".

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/authorization/authorization.scss
> +    border: solid rgba(0, 0, 0, 0.1);
border-width потерялся

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/authorization/authorization.scss
> +    input, button {
Можно лучше. Лучше обращаться к классам, а не к тегам https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/authorization/authorization.scss
> +    height: 450px;
Хорошее разделение правил пустой строкой, мне нравится. Можно ещё разделить позиционирование и визуальные характеристики блока тоже пустой строкой

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/authorization/authorization.tmpl.js
> +export const buildHtmlAuthorization = () => {
Можно лучше. Стоит придерживаться какого- то определенного стиля. Прошлые компоненты создавались через export const field = ({name, placeholder, klass}) => fieldTmpl({...}), а тут с export const buildHtmlAuthorization = () => { return ... }

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/chats/chats.hbs
> +                <img class='chat-view__form-message-icon' src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAOEAAADhCAMAAAAJbSJIAAAAgVBMVEX///8AAAD7+/vCwsLs7Ozk5OTx8fGjo6OmpqbAwMBJSUkzMzP5+flYWFhxcX
Может вынести картинку отдельно можно, а не в шаблоне? Кстати, alt пустая строка не очень хорошо. В данном случае скорее всего иконку нужно скрыть от скрин ридеров добавивь атрибут aria-hidden почитать тут можно https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-hidden. Про alt тут https://htmlacademy.ru/blog/articles/alt-text

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/chats/chats.hbs
> +                <a href="/profile"><img src="https://img2.freepng.ru/20180425/qzq/kisspng-computer-icons-menu-bar-icon-design-hamburger-butt-5ae053e44abbe3.3712052415246509803061.jpg" alt="avatar" wi
Код стайл. СТоит переносить теги на новые строчки. Если атрибутов у тега слишком много их тож можно писать с новой строки

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/chats/chats.scss
> +    div:first-child {
Про теги писал выше

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/chats/chats.tmpl.js
> +//  в дальнейшем будем получать список по api сервера из базы данных.
Можно лучше. Мне помогает если Я пишу такие комменты, добавлять перед ними TODO -это подсвечивает IDE и потом по поиску можно найти что нужно сделать какие были долги. 2) моковые данные лучше хранить в отдельном файле и не засорять ими компонент, а использовать import

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/chats/chats.tmpl.js
> +    chats.list.forEach(function(item, i, arr) {
Внутри используется только item, зачем параметры i и arr?

2022-04-24 13:39 UTC, Rodion-progs commented on src/pages/chats/chats.tmpl.js
> +        chats_list_html += (chat_item(item))
Если chat_item(item) возвращает строку, то это достаточно может быть тяжелой операцией, на каждом сообщение контенировать эти строки. Вариант можно попробовать создать массив chatList в него на каждой итерации пушить chatList.push(chat_item(item)), а потом вывести chatsList: chatList.join(''). Если правильно понял что тут происходит то так

2022-04-24 13:59 UTC, Rodion-progs requested changes
Из критичного стоит поправить сейчас это убрать папку dist из гита и поравить подключение css в index.html

2022-04-25 15:16 UTC, snblack commented
@Rodion-progs 
Поправил

2022-04-26 06:12 UTC, Rodion-progs reviewed
Отлично

2022-04-26 06:12 UTC, Rodion-progs commented on src/index.js
> +switch(current_path) {
Можно лучше. Тут производительнее будет если обращаться по ключу к темлейту. Пример: const tmp = { "registration" : buildHtmlRegistration(),  authorization: buildHtmlAuthorization(), ... }  - root.innerHTML = tmp[current_path] || tmp.authorization. Это можно отложить, пока. И сделать если будет этап оптимизации, так как обращение по ключу более дешевая операция чем switch

2022-04-26 06:12 UTC, Rodion-progs approved these changes

2022-05-10 13:19 UTC, merged