Реализация 3 спринта
koracell/middle.messenger.praktikum.yandex pull request #3
Opened 2022-06-02 23:09 UTC by snblack

2022-06-13 09:56 UTC, podlovchenko requested changes
Привет, задание не доделано
1. Нет редиректа на страницу чатов, если пользователь уже в системе
2. Нет возможности изменить аватар
3. Нет возможности сменить пароль
4. Нет валидации на странице изменения профиля
5. Не выбираются чаты
6. Нельзя отправить сообщения
7. Нет выходов из модального окна
8. Нельзя разлогиниться

2022-06-13 09:56 UTC, podlovchenko commented on src/components/modalAddDeleteUser/modal.scss
> +    background-color: rgba(0, 0, 0, 0.4);
?

2022-06-13 09:56 UTC, podlovchenko commented on src/controllers/AuthController.ts
> +    }
Код повторяется, можно было бы вынести в отдельную функцию

2022-06-13 09:56 UTC, podlovchenko commented on src/api/BaseAPI.ts
> +  // update() { throw new Error('Not implemented') }
Закомментированный код лучше не оставлять

2022-06-13 09:56 UTC, podlovchenko commented on src/api/BaseAPI.ts
> +import HTTPTransport from "./HTTPTransport";
Было бы хорошо добавить prettier, где-то используются двойные, где-то одинарные кавычки

2022-06-13 09:56 UTC, podlovchenko commented on package.json
>      "start": "parcel build index.html && parcel index.html -p 3000"
Стоит добавить команды для линтеров

2022-06-13 09:56 UTC, podlovchenko commented on package.json
>      "start": "parcel build index.html && parcel index.html -p 3000"
И проверку через tsc

2022-06-13 09:56 UTC, podlovchenko commented on babel.config.js
> +};
Этот файл не нужен

2022-06-21 09:22 UTC, podlovchenko commented
Привет
При входе в систему урл меняется на chats, но контент не перерендеривается, при обновлении корректно отображается
Нет редиректа, если пользователь уже в системе (точнее есть, но контент также не обновлется)
Аватары не отображаются
<img width="286" alt="Снимок экрана 2022-06-21 в 12 21 22" src="https://user-images.githubusercontent.com/22602747/174765334-6fb8b6e7-017e-46a6-b068-ec16344e785f.png">
Ошибки typescript также остались, где-то нет импорта типов

2022-06-21 09:24 UTC, snblack commented
Это все что нужно поправить для апрува?

2022-06-21 09:25 UTC, podlovchenko commented
Перед сдаче пройдись по всем пунктам задания и проверь выполнены ли они

2022-06-22 08:42 UTC, podlovchenko commented
Работу принимаю

2022-06-26 09:17 UTC, merged